export {default as Home} from './Home/Home'
export {default as StockList} from './StockList/StockList'
export {default as Login} from './Login/Login'
export {default as Register} from './Register/Register'
export {default as NotFound} from './NotFound/NotFound'